name: vivu_travel
description: "A travel planning mobile app with clean architecture."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.0.0
  dio: ^5.7.0
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.3.2
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  path: ^1.9.1
  mapbox_maps_flutter: ^2.11.0
  geolocator: ^14.0.2
  cached_network_image: ^3.4.1
  signalr_netcore: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # Example fonts configuration
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
